-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 13:21:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `market` DEFAULT CHARACTER SET utf8 ;
USE `market` ;

-- -----------------------------------------------------
-- Table `market`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`customer` (
  `customer_id` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pword` VARCHAR(45) NULL,
  `balance` INT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`cart` (
  `cart_id` INT NOT NULL,
  `customer_id` INT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `market`.`customer` (`customer_id`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`category` (
  `idcategory` INT NOT NULL,
  `Cname` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`product` (
  `product_id` INT NOT NULL,
  `Pname` VARCHAR(45) NULL,
  `category_id` INT NULL,
  `price` DECIMAL(15,2) NULL,
  `stock` INT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `category_id_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `market`.`category` (`idcategory`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`cart_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`cart_product` (
  `p_id` INT NOT NULL,
  `c_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`p_id`, `c_id`),
  INDEX `p_id_idx` (`p_id` ASC) VISIBLE,
  INDEX `c_id_idx` (`c_id` ASC) VISIBLE,
  CONSTRAINT `p_id`
    FOREIGN KEY (`p_id`)
    REFERENCES `market`.`product` (`product_id`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `c_id`
    FOREIGN KEY (`c_id`)
    REFERENCES `market`.`cart` (`cart_id`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`order` (
  `order_id` INT NOT NULL,
  `cust_id` INT NULL,
  `ordered_at` DATETIME NULL,
  `total_amount` DECIMAL(15,2) NULL,
  PRIMARY KEY (`order_id`),
  INDEX `cust_id_idx` (`cust_id` ASC) VISIBLE,
  CONSTRAINT `cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `market`.`customer` (`customer_id`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`order_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`order_product` (
  `pro_id` INT NOT NULL,
  `o_id` INT NOT NULL,
  `quantity` INT NULL,
  PRIMARY KEY (`pro_id`, `o_id`),
  INDEX `pro_id_idx` (`pro_id` ASC) VISIBLE,
  INDEX `o_id_idx` (`o_id` ASC) VISIBLE,
  CONSTRAINT `pro_id`
    FOREIGN KEY (`pro_id`)
    REFERENCES `market`.`product` (`product_id`)
    ON DELETE cascade
    ON UPDATE cascade,
  CONSTRAINT `o_id`
    FOREIGN KEY (`o_id`)
    REFERENCES `market`.`order` (`order_id`)
    ON DELETE cascade
    ON UPDATE cascade)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`admin` (
  `idadmin` INT NOT NULL,
  `Fname` VARCHAR(45) NULL,
  `Lname` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pword` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `market`.`System_wallet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `market`.`System_wallet` (
  `balance` INT NOT NULL,
  PRIMARY KEY (`balance`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
alter table product add status varchar(10);
alter table category add status varchar(10);
alter table customer add unique(userName);